export const messageConst = {
  // common
  MG_02: 'Mất kết nối Internet, vui lòng thử lại sau!',
  MG_03: 'Bạn có chắc chán muốn xóa?',
  MG_04: 'Xóa thành công.',
  MG_05: 'Xóa thất bại.',
  MG_06: 'Email hoặc Mật khẩu nhập không chính xác.',
  MG_07: 'Đăng nhập thành công!',
  MG_08: 'Đăng nhập thất bại.',
  MG_09: 'Email không tồn tại trong hệ thống.',
  MG_10: 'Gửi thông tin thành công!',
  MG_11: 'Gửi thông tin thất bại.',
  MG_12: 'Mật khẩu mới phải ít nhất từ 8 ký tự, chứa cả chữ cái, chữ số và ký tự in hoa.',
  MG_13: 'Nhập lại mật khẩu không trùng với mật khẩu mới.',
  MG_14: 'Đổi mật khẩu thành công',
  MG_15: 'Đổi mật khẩu thất bại.',
  MG_16: 'Email nhập không đúng định dạng.',
  MG_17: 'Ngày sinh nhập không đúng định dạng DD/MM/YYYY.',
  MG_18: 'Avata chỉ được chọn các file: png, pdf, jpg… ',
  MG_19: 'File avata vượt quá kích thước và dung lượng cho phép.',
  MG_20: 'Mật khẩu cũ không chính xác.',
  MG_21: 'Lưu thành công.',
  MG_22: 'Lưu thất bại.',
  MG_23: 'Số điện thoại đã tồn tại.',
  MG_24: 'Email đã tồn tại.',
  MG_25: 'Thêm chi nhánh thành công',
  MG_26: 'Thêm chi nhánh thất bại.',
  MG_27: 'Thêm đối tác thành công.',
  MG_28: 'Thêm đối tác thất bại.',
  MG_29: 'Lưu đối tác thành công.',
  MG_30: 'Lưu đối tác thất bại.',
  MG_31: 'Lưu nhân viên thành công.',
  MG_32: 'Lưu nhân viên thất bại.',
  MG_33: 'Thêm khách hàng thành công.',
  MG_34: 'Thêm khách hàng thất bại.',
};
